# 2024-03-20 수업내용

## numpy test

In [2]:
import numpy as np

In [4]:
a = np.array(([1,2,3],[4,5,6]))
b = np.array(((4,5,6),(7,8,9)))
print(a)
print(b)
a[1][1] = 3
b[1][1] = 3
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 3 6]]
[[4 5 6]
 [7 3 9]]


## 판다스 테스트

In [4]:
import pandas as pd
url = './data/test.csv'
# csv 파일을 읽어서 데이터프레임으로 변환
df = pd.read_csv(url)
# 데이터프레임의 내용 5줄 출력
df.head(5)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

## 데이터프레임의 내용 뒤에 5줄 출력

In [5]:
# 데이터프레임의 내용 5줄 출력
df.tail(5)

PassengerId  Pclass                          Name     Sex   Age  SibSp  \
413         1305       3            Spector, Mr. Woolf    male   NaN      0   
414         1306       1  Oliva y Ocana, Dona. Fermina  female  39.0      0   
415         1307       3  Saether, Mr. Simon Sivertsen    male  38.5      0   
416         1308       3           Ware, Mr. Frederick    male   NaN      0   
417         1309       3      Peter, Master. Michael J    male   NaN      1   

     Parch              Ticket      Fare Cabin Embarked  
413      0           A.5. 3236    8.0500   NaN        S  
414      0            PC 17758  108.9000  C105        C  
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0              359309    8.0500   NaN        S  
417      1                2668   22.3583   NaN        C

## 데이터프레임의 요약 정보 출력

In [6]:
# 데이터프레임의 요약 정보 출력
df.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

# 판다스로 직접 데이터프레임 생성

In [7]:
#새로운 데이터 프레임 생성
df2 = pd.DataFrame()

#열을 추가한다.
df2['name'] = ['kim', 'lee', 'park', 'song', 'yoon']
df2['age'] = [20, 30, 40, 50, 60]
df2['dept'] = ['컴공', '통계', '수학', '국어', '영어']

#데이터프레임의 내용 출력
df2

name  age dept
0   kim   20   컴공
1   lee   30   통계
2  park   40   수학
3  song   50   국어
4  yoon   60   영어

In [8]:
# 행을 만듭니다.
new_row = pd.Series(['choi', 70, '물리'], index=['name', 'age', 'dept'])
# 데이터프레임에 행을 추가합니다.
df2 = df2.append(new_row, ignore_index=True)
# 데이터프레임의 내용 출력
df2

name  age dept
0   kim   20   컴공
1   lee   30   통계
2  park   40   수학
3  song   50   국어
4  yoon   60   영어
5  choi   70   물리

## 리스트나 튜플을 이용해서 생성

In [9]:
# 리스트나 튜플로 부터 생성
data = {'name': ['kim', 'lee', 'park', 'song', 'yoon'],
        'age': [20, 30, 40, 50, 60],
        'dept': ['컴공', '통계', '수학', '국어', '영어']}
df3 = pd.DataFrame(data)
# 데이터프레임의 내용 출력
df3

name  age dept
0   kim   20   컴공
1   lee   30   통계
2  park   40   수학
3  song   50   국어
4  yoon   60   영어

#ndarray로 부터 생성

In [10]:
import numpy as np

In [11]:
#ndarray로 부터 생성
data = [['kim',38,True],['lee',45,False],['park',13,True],['song',33,False],['yoon',25,True]]
matrix = np.array(data)
df4 = pd.DataFrame(matrix, columns=['name','age','Driver'])
# 데이터프레임의 내용 출력
df4

name age Driver
0   kim  38   True
1   lee  45  False
2  park  13   True
3  song  33  False
4  yoon  25   True

## 딕셔너리로부터 생성

In [12]:
# 딕셔너리로부터 생성
data = {'name': ['kim', 'lee', 'park', 'song', 'yoon'],
        'age': [20, 30, 40, 50, 60],
        'Driver': [True, False, True, False, True]}
df5 = pd.DataFrame(data)
# 데이터프레임의 내용 출력
df5

name  age  Driver
0   kim   20    True
1   lee   30   False
2  park   40    True
3  song   50   False
4  yoon   60    True

## 딕셔너리로 이루어진 리스트로부터 생성

In [13]:
# 딕셔너리로 이루어진 리스트로부터 생성
data = [{'name': 'kim', 'age': 20, 'Driver': True},
        {'name': 'lee', 'age': 30, 'Driver': False},
        {'name': 'park', 'age': 40, 'Driver': True},
        {'name': 'song', 'age': 50, 'Driver': False},
        {'name': 'yoon', 'age': 60, 'Driver': True}]
df6 = pd.DataFrame(data)
# 데이터프레임의 내용 출력
df6

name  age  Driver
0   kim   20    True
1   lee   30   False
2  park   40    True
3  song   50   False
4  yoon   60    True

# Series
## 시리즈는 1차원 데이터를 저장하기 위한 데이터 구조 이다.

In [14]:
import pandas as pd
# 시리즈 생성
dat = pd.Series([1, 3, 5, 7, 9])
# 시리즈의 내용 출력
dat

0    1
1    3
2    5
3    7
4    9
dtype: int64

## 시리즈로 저장된 데이터의 내용은 다음과 같이 value로 확인할 수있다.

In [15]:
dat.values

array([1, 3, 5, 7, 9], dtype=int64)

Series는 다양한 객체를 데이터로 저장할 수 있다. 또한 모든 요소가 같은 데이터 타입일 필요도 없다.

In [16]:
import numpy as np
# 시리즈 생성
dat2 = pd.Series(np.array([1,3,np.nan,12]))
dat3 = pd.Series(['aa', 'bb', 'c', 'd'])
dat4 = pd.Series([1, 'aa', 2.34, 'd'])

아래와 같은 방법으로 레이블을 지정해줄 수 있다.

In [17]:
dat5 = pd.Series([1, 3, 6, 12], index=[1,10,20,33])
dat6 = pd.Series([1, 3, 6, 12], index=['a','b','c','a'])
dat7 = pd.Series({'a':1, 'b':3, 'c':6, 'd':12})

출력

In [18]:
print(dat2)
print(dat3)
print(dat4)
print(dat5)
print(dat6)
print(dat7)

0     1.0
1     3.0
2     NaN
3    12.0
dtype: float64
0    aa
1    bb
2     c
3     d
dtype: object
0       1
1      aa
2    2.34
3       d
dtype: object
1      1
10     3
20     6
33    12
dtype: int64
a     1
b     3
c     6
a    12
dtype: int64
a     1
b     3
c     6
d    12
dtype: int64


레이블 값 변경

In [19]:
dat2.index = ['uno', 'dus', 'trois', 'quatre']
print(dat2)

uno        1.0
dus        3.0
trois      NaN
quatre    12.0
dtype: float64


# DataFrame
DataFrame은 레이블을 갖는 2차원 데이터 구조이다.
NumPy로부터 2차원 ndarray를 그대로 입력하는 것이 가능하다.
시리즈와 마찬가지로 레이블 입력이 가능하며, 2차원이므로 라인 레이블과 컬럼
레이블을 지정할 수 있다

In [20]:
df3=pd.DataFrame(np.random.randn(6,2),
        index=[[1,1,2,2,3,3],[1,2,1,2,1,2]],
        columns=['item1','item2'])
print(df3)

        item1     item2
1 1  0.317237  0.769399
  2 -0.239462  0.247276
2 1  0.686877 -1.139116
  2  1.830998 -0.374574
3 1  0.568349 -1.099587
  2 -1.739699 -0.000714


head()와 tail()을 이용하여 데이터프레임의 내용을 확인할 수 있다.

In [21]:
df.head(2) # 처음 2줄
df.tail(2) # 마지막 2줄

PassengerId  Pclass                      Name   Sex  Age  SibSp  Parch  \
416         1308       3       Ware, Mr. Frederick  male  NaN      0      0   
417         1309       3  Peter, Master. Michael J  male  NaN      1      1   

     Ticket     Fare Cabin Embarked  
416  359309   8.0500   NaN        S  
417    2668  22.3583   NaN        C

describe()를 이용하여 데이터프레임의 요약 정보를 확인할 수 있다.

In [22]:
df.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

데이터프레임의 차원을 확인합니다.

In [23]:
print(df.shape)

(418, 11)


loc나 iloc 메서드를 사용해 하나 이상의 행이나 값을 선택

In [24]:
print(df.iloc[0]) # 첫번째 행
print(df.iloc[1:4]) # 두번째부터 네번째 행 총 3개

# 마지막 행 포함
print(df.loc[0]) # 첫번째 행
print(df.loc[1:4]) # 두번째부터 네번째 행 총 4개

PassengerId                 892
Pclass                        3
Name           Kelly, Mr. James
Sex                        male
Age                        34.5
SibSp                         0
Parch                         0
Ticket                   330911
Fare                     7.8292
Cabin                       NaN
Embarked                      Q
Name: 0, dtype: object
   PassengerId  Pclass                              Name     Sex   Age  SibSp  \
1          893       3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2          894       2         Myles, Mr. Thomas Francis    male  62.0      0   
3          895       3                  Wirz, Mr. Albert    male  27.0      0   

   Parch  Ticket    Fare Cabin Embarked  
1      0  363272  7.0000   NaN        S  
2      0  240276  9.6875   NaN        Q  
3      0  315154  8.6625   NaN        S  
PassengerId                 892
Pclass                        3
Name           Kelly, Mr. James
Sex                        male
Age 

loc나 iloc 메서드를 사용해 하나 이상의 행이나 값을 선택

In [25]:
# 인덱스를 설정합니다.
index_name_df=df.set_index(df['Name'])
index_name_df

PassengerId  Pclass  \
Name                                                                
Kelly, Mr. James                                      892       3   
Wilkes, Mrs. James (Ellen Needs)                      893       3   
Myles, Mr. Thomas Francis                             894       2   
Wirz, Mr. Albert                                      895       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896       3   
...                                                   ...     ...   
Spector, Mr. Woolf                                   1305       3   
Oliva y Ocana, Dona. Fermina                         1306       1   
Saether, Mr. Simon Sivertsen                         1307       3   
Ware, Mr. Frederick                                  1308       3   
Peter, Master. Michael J                             1309       3   

                                                                                      Name  \
Name                                                                                         
Kelly, Mr. James                                                          Kelly, Mr. James   
Wilkes, Mrs. James (Ellen Needs)                          Wilkes, Mrs. James (Ellen Needs)   
Myles, Mr. Thomas Francis                                        Myles, Mr. Thomas Francis   
Wirz, Mr. Albert                                                          Wirz, Mr. Albert   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
...                                                                                    ...   
Spector, Mr. Woolf                                                      Spector, Mr. Woolf   
Oliva y Ocana, Dona. Fermina                                  Oliva y Ocana, Dona. Fermina   
Saether, Mr. Simon Sivertsen                                  Saether, Mr. Simon Sivertsen   
Ware, Mr. Frederick                                                    Ware, Mr. Frederick   
Peter, Master. Michael J                                          Peter, Master. Michael J   

                                                 Sex   Age  SibSp  Parch  \
Name                                                                       
Kelly, Mr. James                                male  34.5      0      0   
Wilkes, Mrs. James (Ellen Needs)              female  47.0      1      0   
Myles, Mr. Thomas Francis                       male  62.0      0      0   
Wirz, Mr. Albert                                male  27.0      0      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
...                                              ...   ...    ...    ...   
Spector, Mr. Woolf                              male   NaN      0      0   
Oliva y Ocana, Dona. Fermina                  female  39.0      0      0   
Saether, Mr. Simon Sivertsen                    male  38.5      0      0   
Ware, Mr. Frederick                             male   NaN      0      0   
Peter, Master. Michael J                        male   NaN      1      1   

                                                          Ticket      Fare  \
Name                                                                         
Kelly, Mr. James                                          330911    7.8292   
Wilkes, Mrs. James (Ellen Needs)                          363272    7.0000   
Myles, Mr. Thomas Francis                                 240276    9.6875   
Wirz, Mr. Albert                                          315154    8.6625   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)             3101298   12.2875   
...                                                          ...       ...   
Spector, Mr. Woolf                                     A.5. 3236    8.0500   
Oliva y Ocana, Dona. Fermina                            PC 17758  108.9000   
Saether, Mr. Simon Sivertsen                  SOTON/O.Q. 3101262    7.2500   
Ware, Mr. Frederick                                       359309    8.0500   


In [26]:
# 행을 확인합니다.
index_name_df.loc['Wirz, Mr. Albert']

PassengerId                 895
Pclass                        3
Name           Wirz, Mr. Albert
Sex                        male
Age                          27
SibSp                         0
Parch                         0
Ticket                   315154
Fare                     8.6625
Cabin                       NaN
Embarked                      S
Name: Wirz, Mr. Albert, dtype: object

In [27]:
# Wirz, Mr. Albert 이전까지 Sex와 Age 열만 선택합니다.
index_name_df.loc[:'Wirz, Mr. Albert','Sex':'Age']

Sex   Age
Name                                          
Kelly, Mr. James                    male  34.5
Wilkes, Mrs. James (Ellen Needs)  female  47.0
Myles, Mr. Thomas Francis           male  62.0
Wirz, Mr. Albert                    male  27.0

데이터프레임 객체에 슬라이싱 사용하면 행을 선택. 인덱싱을 사용하면 열을 선택

In [28]:
# df[:4]와 동일합니다.
index_name_df[:'Wirz, Mr. Albert']

PassengerId  Pclass  \
Name                                                    
Kelly, Mr. James                          892       3   
Wilkes, Mrs. James (Ellen Needs)          893       3   
Myles, Mr. Thomas Francis                 894       2   
Wirz, Mr. Albert                          895       3   

                                                              Name     Sex  \
Name                                                                         
Kelly, Mr. James                                  Kelly, Mr. James    male   
Wilkes, Mrs. James (Ellen Needs)  Wilkes, Mrs. James (Ellen Needs)  female   
Myles, Mr. Thomas Francis                Myles, Mr. Thomas Francis    male   
Wirz, Mr. Albert                                  Wirz, Mr. Albert    male   

                                   Age  SibSp  Parch  Ticket    Fare Cabin  \
Name                                                                         
Kelly, Mr. James                  34.5      0      0  330911  7.8292   NaN   
Wilkes, Mrs. James (Ellen Needs)  47.0      1      0  363272  7.0000   NaN   
Myles, Mr. Thomas Francis         62.0      0      0  240276  9.6875   NaN   
Wirz, Mr. Albert                  27.0      0      0  315154  8.6625   NaN   

                                 Embarked  
Name                                       
Kelly, Mr. James                        Q  
Wilkes, Mrs. James (Ellen Needs)        S  
Myles, Mr. Thomas Francis               Q  
Wirz, Mr. Albert                        S

In [29]:
index_name_df[['Sex','Age']].head(2)

Sex   Age
Name                                          
Kelly, Mr. James                    male  34.5
Wilkes, Mrs. James (Ellen Needs)  female  47.0

## 조건에 따라 행선택

In [30]:
# sex 열이 female인 행을 선택합니다.
index_name_df[index_name_df['Sex']=='female'].head(2)

PassengerId  Pclass  \
Name                                                                
Wilkes, Mrs. James (Ellen Needs)                      893       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896       3   

                                                                                      Name  \
Name                                                                                         
Wilkes, Mrs. James (Ellen Needs)                          Wilkes, Mrs. James (Ellen Needs)   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   

                                                 Sex   Age  SibSp  Parch  \
Name                                                                       
Wilkes, Mrs. James (Ellen Needs)              female  47.0      1      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

                                               Ticket     Fare Cabin Embarked  
Name                                                                           
Wilkes, Mrs. James (Ellen Needs)               363272   7.0000   NaN        S  
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  3101298  12.2875   NaN        S

In [31]:
# female이면서 Age가 65이상인 행을 선택합니다.
index_name_df[(index_name_df['Sex']=='female') & (index_name_df['Age']>=65)]

PassengerId  Pclass  \
Name                                                                      
Cavendish, Mrs. Tyrell William (Julia Florence ...          988       1   

                                                                                                 Name  \
Name                                                                                                    
Cavendish, Mrs. Tyrell William (Julia Florence ...  Cavendish, Mrs. Tyrell William (Julia Florence...   

                                                       Sex   Age  SibSp  \
Name                                                                      
Cavendish, Mrs. Tyrell William (Julia Florence ...  female  76.0      1   

                                                    Parch Ticket   Fare Cabin  \
Name                                                                            
Cavendish, Mrs. Tyrell William (Julia Florence ...      0  19877  78.85   C46   

                                                   Embarked  
Name                                                         
Cavendish, Mrs. Tyrell William (Julia Florence ...        S

문자열 다룰 때는 str 메서드 이용
str.find는 특정 문자 포함하는 열 추출. 문자열 포함되어있으면 열 인덱스 반환.
포함되어 있지 않을 경우 -1 반환

In [32]:
# Mr. 포함된 행을 선택합니다.
index_name_df['Name'].str.find('Mr.')

Name
Kelly, Mr. James                                7
Wilkes, Mrs. James (Ellen Needs)               -1
Myles, Mr. Thomas Francis                       7
Wirz, Mr. Albert                                6
Hirvonen, Mrs. Alexander (Helga E Lindqvist)   -1
                                               ..
Spector, Mr. Woolf                              9
Oliva y Ocana, Dona. Fermina                   -1
Saether, Mr. Simon Sivertsen                    9
Ware, Mr. Frederick                             6
Peter, Master. Michael J                       -1
Name: Name, Length: 418, dtype: int64

In [33]:
index_name_df[index_name_df['Name'].str.find('Mr.')>-1].head(3)

PassengerId  Pclass                       Name  \
Name                                                                        
Kelly, Mr. James                   892       3           Kelly, Mr. James   
Myles, Mr. Thomas Francis          894       2  Myles, Mr. Thomas Francis   
Wirz, Mr. Albert                   895       3           Wirz, Mr. Albert   

                            Sex   Age  SibSp  Parch  Ticket    Fare Cabin  \
Name                                                                        
Kelly, Mr. James           male  34.5      0      0  330911  7.8292   NaN   
Myles, Mr. Thomas Francis  male  62.0      0      0  240276  9.6875   NaN   
Wirz, Mr. Albert           male  27.0      0      0  315154  8.6625   NaN   

                          Embarked  
Name                                
Kelly, Mr. James                 Q  
Myles, Mr. Thomas Francis        Q  
Wirz, Mr. Albert                 S

## 값 치환
Sex열이 female인 행의 Sex열 값을 Woman로 변경합니다.

In [34]:
# 값을 치환하고 두개의 행을 출력합니다.
index_name_df["Sex"].replace("female","Woman").head(2)

Name
Kelly, Mr. James                     male
Wilkes, Mrs. James (Ellen Needs)    Woman
Name: Sex, dtype: object

Sex열이 female인 행의 Sex열 값을 Woman로 변경합니다.

In [35]:
# female 과 male 을 woman과 man으로 치환합니다.
index_name_df["Sex"].replace(["female","male"],["Woman","Man"]).head(5)

Name
Kelly, Mr. James                                  Man
Wilkes, Mrs. James (Ellen Needs)                Woman
Myles, Mr. Thomas Francis                         Man
Wirz, Mr. Albert                                  Man
Hirvonen, Mrs. Alexander (Helga E Lindqvist)    Woman
Name: Sex, dtype: object

데이터 프레임 전체에서 값 변경

In [36]:
# 값을 치환하고 두개의 행을 출력합니다.
index_name_df.replace(0,"Zero").head(2)

PassengerId  Pclass  \
Name                                                    
Kelly, Mr. James                          892       3   
Wilkes, Mrs. James (Ellen Needs)          893       3   

                                                              Name     Sex  \
Name                                                                         
Kelly, Mr. James                                  Kelly, Mr. James    male   
Wilkes, Mrs. James (Ellen Needs)  Wilkes, Mrs. James (Ellen Needs)  female   

                                   Age SibSp Parch  Ticket    Fare Cabin  \
Name                                                                       
Kelly, Mr. James                  34.5  Zero  Zero  330911  7.8292   NaN   
Wilkes, Mrs. James (Ellen Needs)  47.0     1  Zero  363272       7   NaN   

                                 Embarked  
Name                                       
Kelly, Mr. James                        Q  
Wilkes, Mrs. James (Ellen Needs)        S

한번에 여러 개의 값을 동일하게 변경

In [37]:
# female 과 male을 person으로 치환합니다.
index_name_df.replace(["female","male"],"person").head(5)

PassengerId  Pclass  \
Name                                                                
Kelly, Mr. James                                      892       3   
Wilkes, Mrs. James (Ellen Needs)                      893       3   
Myles, Mr. Thomas Francis                             894       2   
Wirz, Mr. Albert                                      895       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896       3   

                                                                                      Name  \
Name                                                                                         
Kelly, Mr. James                                                          Kelly, Mr. James   
Wilkes, Mrs. James (Ellen Needs)                          Wilkes, Mrs. James (Ellen Needs)   
Myles, Mr. Thomas Francis                                        Myles, Mr. Thomas Francis   
Wirz, Mr. Albert                                                          Wirz, Mr. Albert   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   

                                                 Sex   Age  SibSp  Parch  \
Name                                                                       
Kelly, Mr. James                              person  34.5      0      0   
Wilkes, Mrs. James (Ellen Needs)              person  47.0      1      0   
Myles, Mr. Thomas Francis                     person  62.0      0      0   
Wirz, Mr. Albert                              person  27.0      0      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  person  22.0      1      1   

                                               Ticket     Fare Cabin Embarked  
Name                                                                           
Kelly, Mr. James                               330911   7.8292   NaN        Q  
Wilkes, Mrs. James (Ellen Needs)               363272   7.0000   NaN        S  
Myles, Mr. Thomas Francis                      240276   9.6875   NaN        Q  
Wirz, Mr. Albert                               315154   8.6625   NaN        S  
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  3101298  12.2875   NaN        S

딕셔너리로 바꿀 값을 각각 매핑하여 전달 가능

In [38]:
# female 을 1을 바꾸고 male을 0으로 바꿉니다.
index_name_df.replace({"female":1,"male":0}).head(5)

PassengerId  Pclass  \
Name                                                                
Kelly, Mr. James                                      892       3   
Wilkes, Mrs. James (Ellen Needs)                      893       3   
Myles, Mr. Thomas Francis                             894       2   
Wirz, Mr. Albert                                      895       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896       3   

                                                                                      Name  \
Name                                                                                         
Kelly, Mr. James                                                          Kelly, Mr. James   
Wilkes, Mrs. James (Ellen Needs)                          Wilkes, Mrs. James (Ellen Needs)   
Myles, Mr. Thomas Francis                                        Myles, Mr. Thomas Francis   
Wirz, Mr. Albert                                                          Wirz, Mr. Albert   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   

                                              Sex   Age  SibSp  Parch  \
Name                                                                    
Kelly, Mr. James                                0  34.5      0      0   
Wilkes, Mrs. James (Ellen Needs)                1  47.0      1      0   
Myles, Mr. Thomas Francis                       0  62.0      0      0   
Wirz, Mr. Albert                                0  27.0      0      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1  22.0      1      1   

                                               Ticket     Fare Cabin Embarked  
Name                                                                           
Kelly, Mr. James                               330911   7.8292   NaN        Q  
Wilkes, Mrs. James (Ellen Needs)               363272   7.0000   NaN        S  
Myles, Mr. Thomas Francis                      240276   9.6875   NaN        Q  
Wirz, Mr. Albert                               315154   8.6625   NaN        S  
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  3101298  12.2875   NaN        S

## 열이름 바꾸기

In [40]:
# 열이름을 바꾸고 두개의 행을 출력합니다.
index_name_df.rename(columns={'Pclass':'Passenger Class'}).head(2)

PassengerId  Passenger Class  \
Name                                                             
Kelly, Mr. James                          892                3   
Wilkes, Mrs. James (Ellen Needs)          893                3   

                                                              Name     Sex  \
Name                                                                         
Kelly, Mr. James                                  Kelly, Mr. James    male   
Wilkes, Mrs. James (Ellen Needs)  Wilkes, Mrs. James (Ellen Needs)  female   

                                   Age  SibSp  Parch  Ticket    Fare Cabin  \
Name                                                                         
Kelly, Mr. James                  34.5      0      0  330911  7.8292   NaN   
Wilkes, Mrs. James (Ellen Needs)  47.0      1      0  363272  7.0000   NaN   

                                 Embarked  
Name                                       
Kelly, Mr. James                        Q  
Wilkes, Mrs. James (Ellen Needs)        S

In [41]:
# 열의 이름을 2개 바꾸고 두개의 행을 출력합니다.
index_name_df.rename(columns={'Pclass':'Passenger Class','Sex':'Gender'}).head(2)

PassengerId  Passenger Class  \
Name                                                             
Kelly, Mr. James                          892                3   
Wilkes, Mrs. James (Ellen Needs)          893                3   

                                                              Name  Gender  \
Name                                                                         
Kelly, Mr. James                                  Kelly, Mr. James    male   
Wilkes, Mrs. James (Ellen Needs)  Wilkes, Mrs. James (Ellen Needs)  female   

                                   Age  SibSp  Parch  Ticket    Fare Cabin  \
Name                                                                         
Kelly, Mr. James                  34.5      0      0  330911  7.8292   NaN   
Wilkes, Mrs. James (Ellen Needs)  47.0      1      0  363272  7.0000   NaN   

                                 Embarked  
Name                                       
Kelly, Mr. James                        Q  
Wilkes, Mrs. James (Ellen Needs)        S

In [46]:
# columns 속성값 변경 가능
index_name_df.columns=['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked']
index_name_df.head(2)

PassengerId  Pclass  \
Name                                                    
Kelly, Mr. James                          892       3   
Wilkes, Mrs. James (Ellen Needs)          893       3   

                                                              Name     Sex  \
Name                                                                         
Kelly, Mr. James                                  Kelly, Mr. James    male   
Wilkes, Mrs. James (Ellen Needs)  Wilkes, Mrs. James (Ellen Needs)  female   

                                   Age  SibSp  Parch  Ticket    Fare Cabin  \
Name                                                                         
Kelly, Mr. James                  34.5      0      0  330911  7.8292   NaN   
Wilkes, Mrs. James (Ellen Needs)  47.0      1      0  363272  7.0000   NaN   

                                 Embarked  
Name                                       
Kelly, Mr. James                        Q  
Wilkes, Mrs. James (Ellen Needs)        S

## 행이름 바꾸기

In [49]:
# 인덱스 0을 -1로 바꿉니다.
index_name_df.rename(index={0:-1}).head(2)

PassengerId  Pclass  \
Name                                                    
Kelly, Mr. James                          892       3   
Wilkes, Mrs. James (Ellen Needs)          893       3   

                                                              Name     Sex  \
Name                                                                         
Kelly, Mr. James                                  Kelly, Mr. James    male   
Wilkes, Mrs. James (Ellen Needs)  Wilkes, Mrs. James (Ellen Needs)  female   

                                   Age  SibSp  Parch  Ticket    Fare Cabin  \
Name                                                                         
Kelly, Mr. James                  34.5      0      0  330911  7.8292   NaN   
Wilkes, Mrs. James (Ellen Needs)  47.0      1      0  363272  7.0000   NaN   

                                 Embarked  
Name                                       
Kelly, Mr. James                        Q  
Wilkes, Mrs. James (Ellen Needs)        S

In [50]:
# 열이름을 소문자로 바꿉니다.
index_name_df.rename(str.lower, axis='columns').head(2)

passengerid  pclass  \
Name                                                    
Kelly, Mr. James                          892       3   
Wilkes, Mrs. James (Ellen Needs)          893       3   

                                                              name     sex  \
Name                                                                         
Kelly, Mr. James                                  Kelly, Mr. James    male   
Wilkes, Mrs. James (Ellen Needs)  Wilkes, Mrs. James (Ellen Needs)  female   

                                   age  sibsp  parch  ticket    fare cabin  \
Name                                                                         
Kelly, Mr. James                  34.5      0      0  330911  7.8292   NaN   
Wilkes, Mrs. James (Ellen Needs)  47.0      1      0  363272  7.0000   NaN   

                                 embarked  
Name                                       
Kelly, Mr. James                        Q  
Wilkes, Mrs. James (Ellen Needs)        S

# 기초통계 구하기
최댓값, 최솟값, 평균, 합계싼 및 개수 세기

In [51]:
print("최댓값", index_name_df['Age'].max())
print("최솟값", index_name_df['Age'].min())
print("평균", index_name_df['Age'].mean())
print("합계", index_name_df['Age'].sum())
print("개수", index_name_df['Age'].count())

print("분산", index_name_df['Age'].var())
print("표준편차", index_name_df['Age'].std())
print("첨도", index_name_df['Age'].kurt())
print("왜도", index_name_df['Age'].skew())
print("평균의 표준오차", index_name_df['Age'].sem())
print("최빈값", index_name_df['Age'].mode())
print("중간값", index_name_df['Age'].median())

최댓값 76.0
최솟값 0.17
평균 30.272590361445783
합계 10050.5
개수 332
분산 201.10669538455943
표준편차 14.181209235624422
첨도 0.08378335153796135
왜도 0.4573612871503845
평균의 표준오차 0.7782949687536385
최빈값 0    21.0
1    24.0
dtype: float64
중간값 27.0


In [52]:
# 수치형 열의 공분산을 계산합니다.
index_name_df.cov()

PassengerId     Pclass         Age     SibSp      Parch  \
PassengerId  14595.166667  -2.720624  -59.369047  0.413669   5.107914   
Pclass          -2.720624   0.708690   -5.906358  0.000820   0.015467   
Age            -59.369047  -5.906358  201.106695 -1.135270  -0.704115   
SibSp            0.413669   0.000820   -1.135270  0.804178   0.270100   
Parch            5.107914   0.015467   -0.704115  0.270100   0.963203   
Fare            55.514238 -27.171232  291.838610  8.607981  12.635175   

                    Fare  
PassengerId    55.514238  
Pclass        -27.171232  
Age           291.838610  
SibSp           8.607981  
Parch          12.635175  
Fare         3125.657074

In [53]:
# 수치형 열의 상관계수를 계산합니다.
index_name_df.corr()

PassengerId    Pclass       Age     SibSp     Parch      Fare
PassengerId     1.000000 -0.026751 -0.034102  0.003818  0.043080  0.008211
Pclass         -0.026751  1.000000 -0.492143  0.001087  0.018721 -0.577147
Age            -0.034102 -0.492143  1.000000 -0.091587 -0.061249  0.337932
SibSp           0.003818  0.001087 -0.091587  1.000000  0.306895  0.171539
Parch           0.043080  0.018721 -0.061249  0.306895  1.000000  0.230046
Fare            0.008211 -0.577147  0.337932  0.171539  0.230046  1.000000